################################################## 
# SOAPTransportService_services_types.py 
# generated by ZSI.generate.wsdl2python
##################################################


import ZSI
import ZSI.TCcompound
from ZSI.schema import LocalElementDeclaration, ElementDeclaration, TypeDefinition, GTD, GED

##############################
# targetNamespace
# http://cima.instrumentmiddleware.org/ws
##############################

class ns0:
    targetNamespace = "http://cima.instrumentmiddleware.org/ws"

    class handleParcel_Dec(ZSI.TC.String, ElementDeclaration):
        literal = "handleParcel"
        schema = "http://cima.instrumentmiddleware.org/ws"
        def __init__(self, **kw):
            kw["pname"] = ("http://cima.instrumentmiddleware.org/ws","handleParcel")
            kw["aname"] = "_handleParcel"
            class IHolder(str): typecode=self
            kw["pyclass"] = IHolder
            IHolder.__name__ = "_handleParcel_immutable_holder"
            ZSI.TC.String.__init__(self, **kw)

    class handleParcelRes_Dec(ZSI.TC.String, ElementDeclaration):
        literal = "handleParcelRes"
        schema = "http://cima.instrumentmiddleware.org/ws"
        def __init__(self, **kw):
            kw["pname"] = ("http://cima.instrumentmiddleware.org/ws","handleParcelRes")
            kw["aname"] = "_handleParcelRes"
            class IHolder(str): typecode=self
            kw["pyclass"] = IHolder
            IHolder.__name__ = "_handleParcelRes_immutable_holder"
            ZSI.TC.String.__init__(self, **kw)

# end class ns0 (tns: http://cima.instrumentmiddleware.org/ws)
