################################################## 
# SOAPTransportService_services.py 
# generated by ZSI.generate.wsdl2python
##################################################


from SOAPTransportService_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI

# Locator
class SOAPTransportServiceLocator:
    CimaWS_address = "http://cima:8080/ws/cima"
    def getCimaWSAddress(self):
        return SOAPTransportServiceLocator.CimaWS_address
    def getCimaWS(self, url=None, **kw):
        return SOAPTransportServiceSoapBindingSOAP(url or SOAPTransportServiceLocator.CimaWS_address, **kw)

# Methods
class SOAPTransportServiceSoapBindingSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: handleParcel
    def handleParcel(self, request):
        if isinstance(request, handleParcel) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="", **kw)
        # no output wsaction
        response = self.binding.Receive(handleParcelResponse.typecode)
        return handleParcelResponse(response)

handleParcel = ns0.handleParcel_Dec().pyclass

handleParcelResponse = ns0.handleParcelRes_Dec().pyclass
